// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMdmD5WWNfGGfVtNTUTs35-cF0-VlDOG4',
    appId: '1:855364517437:android:79d0c039a70a9fdf033454',
    messagingSenderId: '855364517437',
    projectId: 'winter-2024-31dd0',
    storageBucket: 'winter-2024-31dd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi71CnRwOgrBG-wsnIu0p0mswNTg3DPmw',
    appId: '1:855364517437:ios:1e791aed1613a7e3033454',
    messagingSenderId: '855364517437',
    projectId: 'winter-2024-31dd0',
    storageBucket: 'winter-2024-31dd0.firebasestorage.app',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLr5tMXlxjjqvaPNXOuMne-LTvLtTKYSE',
    appId: '1:855364517437:web:3599b73450d097b2033454',
    messagingSenderId: '855364517437',
    projectId: 'winter-2024-31dd0',
    authDomain: 'winter-2024-31dd0.firebaseapp.com',
    storageBucket: 'winter-2024-31dd0.firebasestorage.app',
  );

}